name: Linting
on: [push, pull_request]
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Pylint
        run: |
          pip install pylint
      - name: Run Pylint
        run: |
          pylint app.py
